### ISSUE TITLE
Add more line-coding identities

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#32]
See https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/100

**Comment by sergiobelotti** [comment]
It was agreed to do:

- to introduce a new attribute just for bit rate >= 100G i.e. 100G,200G,300G,400G in layer0-types-ext YANG
- When we need more than line rate (e.g. modulation format) we will use line coding and in this case we can provide just the standard ones.
