### ISSUE TITLE
Shouldn't penalty be a decimal value ?

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#38]
Shouldn't penalty be a decimal value ?

_Originally posted by @EstherLerouzic in https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/36#discussion_r818392648_

**Comment by sergiobelotti** [comment]
Weekly call March 8th:
It should be decimal, and we can add a new typedef  e.g. decimal-in-db  (2 digits).

**Comment by italobusi** [comment]
Already fixed with PR #53
