### ISSUE TITLE
Shouldn't max-diff-group-delay be a decimal value ?

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#39]
shouldn't this be a decimal value ?
unit is missing

_Originally posted by @EstherLerouzic in https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/36#discussion_r818394767_

**Comment by sergiobelotti** [comment]
Weekly call March 8th
pIco-sec is the usual unit. Having integer is acceptable (positive). uint32 can be fine.
