### ISSUE TITLE
identity modulation :  add new modulation formats.

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#41]
The identity modulation is covering almost all modulation formats.  
My proposal is to complete the list adding:
- DPSK (Differential Phase Shift Keying)
- QAM32
- DP-QAM32
- QAM64
- DP-QAM64
- HYBRID modulation format (see also ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#47)
- probabilistic shaping modulation format

Further description will be provided to the above list.

**Comment by egriseri** [comment]
@ggalimba56 for sure we can't fully cover **all** the modulation formats. I also noticed that we included dual carrier format, and this opens to additional complexity (let's imagine a 4 carrier format, and so on)
Anyway, for the probabilistic shaping we can specify the "base" format as 8QAM, 16QAM, 32QAM, 64QAM but I really doubt we should specify the entropy value. What do you think?

**Comment by sergiobelotti** [comment]
Call on 05/24/22: 
The proposal from Gabriel is to add the first 4 modulation formats listed above and leave a part the last two for the moment.
AP Gabriele: to introduce description on the 4 modulation format above and a standard reference (if exists)

**Comment by ggalimba56** [comment]
Here a possible proposal:

  identity DPSK {
    base modulation;
    description
      “DPSK (Differential Phase Shift Keying) modulation";
  }

  identity QAM32 {
    base modulation;
    description
      "QAM32 (32 symbols Quadrature Amplitude Modulation)";
  }

  identity DP-QAM32 {
    base modulation;
    description
      "DP-QAM32 (32 symbols Dual Polarization Quadrature Amplitude 
       Modulation)";
  }

  identity QAM64 {
    base modulation;
    description
      "QAM64 (64 symbols Quadrature Amplitude Modulation)";
  }

  identity DP-QAM64 {
    base modulation;
    description
      "DP-QAM64 (64 symbols Dual Polarization Quadrature Amplitude 
       Modulation)";
  }

**Comment by sergiobelotti** [comment]
@ggalimba56 @egriseri : do you know if a standard reference exists to be added in the description?
