### ISSUE TITLE
operational-mode clarification

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#42]
In the draft there is the Typedef:

```
  typedef operational-mode {
    type string;
    description
      "Organization/vendor specific mode that guarantees 
      interoperability.";
    reference "ITU-T G.698.2 (11/2018)";
  }

```

The operational-mode is NOT mentioned in ITU-T G.698.2 is a vendor specific or organization parameters that should be better specified.   
I’d remove the reference to ITU-T in the above description.

**Comment by italobusi** [comment]
I agree not to reference G.698.2

Should we reference https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-optical-impairment-topology-yang#section-2.5.2 instead?

I think this is the location where the organizational mode is defined

**Comment by sergiobelotti** [comment]
> I agree not to reference G.698.2
> 
> Should we reference https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-optical-impairment-topology-yang#section-2.5.2 instead?
> 
> I think this is the location where the organizational mode is defined

@italobusi @ggalimba56 : I agree on Italo's proposal to reference our draft , this is the place where operational mode is defined : is something has to be added in the description is anyway there that enhancement has to be done.
