### ISSUE TITLE
RFC6205 Reference and frequency definition

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#43]
In the current draft the Typedef:

```
 typedef frequency-thz {
      type decimal64 {
        fraction-digits 6;
      }
      units THz;
      description
        "The DWDM frequency in THz, e.g., 193.112500";
      reference
        "RFC6205: Generalized Labels for
        Lambda-Switch-Capable (LSC) Label Switching Routers";
  }
  typedef frequency-ghz {
      type decimal64 {
        fraction-digits 3;
      }
      units GHz;
      description
        "The DWDM frequency in GHz, e.g., 193112.500";
      reference
        "RFC6205: Generalized Labels for
        Lambda-Switch-Capable (LSC) Label Switching Routers";
  }    

```

If we refer to 6205 we should define the frequency as: Frequency (THz) = 193.1 THz + n * channel spacing (THz)    and the define the concept of n, m, granularity, etc.

**Comment by EstherLerouzic** [comment]
I agree, the n and m refer to the media channel , so for center and width on the filters not of the OTSi. But OTSi carriers may not aligned on this grid. this is shown in our draft fig  3. I think we should remove this ref and maybe replace it with ref G.807 fig 7-2?

**Comment by sergiobelotti** [comment]
I think here we just trying to define a "type" THz or GHz and use that in other definition .
The intention is not to define what is the "nominal central frequency" as you report above. Nominal central Frequency is defined in the context of N value definition see RFC9093 e.g. dwdm-n.
I suggest here simply to delete the reference that is not needed here .

**Comment by sergiobelotti** [comment]
Call on 05/24/22:
We all agree to just delete the referecne to RFC6205 and leave as it is the rest .
AP: @sergiobelotti @italobusi : to modify YANG in the next PR
