### ISSUE TITLE
“penalty” definition

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#44]
leaf polarization-mode-dispersion {
      type union {
        type decimal64 {
          fraction-digits 2;
          range "0..max";
        }
        type empty;
      }
      units "ps";
      config false;
      mandatory true;
      description "Polarization mode dispersion";
    }
    leaf penalty {
      type union {
        type decimal64 {
          fraction-digits 2;
          range "0..max";
        }
        type empty;
      }
      units "dB";
      config false;
      mandatory true;
      description "Associated penalty on the receiver";
    }
  }  

the above penalty definition is not cleat: e.g. to what parameter is referred ?

**Comment by EstherLerouzic** [comment]
I think it is in the triplet definition:
list of (accumulated CD, accumulated PMD, associated Penalty). penalty in case we have a combinaison of CD and PMD.
We had many discussions on this... 
In this one https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/98
it was concluded to have separate lists.

list of (accumulated effect, associated Penalty), effect could be CD, PMD or PDL

**Comment by sergiobelotti** [comment]
> I think it is in the triplet definition: list of (accumulated CD, accumulated PMD, associated Penalty). penalty in case we have a combinaison of CD and PMD. We had many discussions on this... In this one [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#98](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/98) it was concluded to have separate lists.
> 
> list of (accumulated effect, associated Penalty), effect could be CD, PMD or PDL

We still need to fix this point: with the next PR we need to substitute the triplet as today, with separated lists.

list of (accumulated effect, associated Penalty), effect could be CD, PMD or PDL.
Is, with this modification clear enough the penalty definition?

**Comment by egriseri** [comment]
@ggalimba56 do you mean that one should specify whether the penalty has to be considered Vs Power or OSNR? or are we defining a penalty in term of Q?
I think we (implicitly) considered OSNR penalties so far. A penalty in both OSNR and power is a more precise model but the actual values would depend on the receiver's working point.
Or do we simply evaluate performance degradation (thus a Q penalty)?
In any case I agree we should specify it in the draft.
CC: @sergiobelotti @EstherLerouzic

**Comment by sergiobelotti** [comment]
Call on 05/24/22:
Esther suggested to look at what OpenConfig is doing regarding penalty. The penalty is defined in OSNR and for a given power 

Look at https://ietf.webex.com/ietf-en/url.php?frompanel=false&gourl=https%3A%2F%2Fgithub.com%2Fopenconfig%2Fpublic%2Fblob%2Fmaster%2Frelease%2Fmodels%2Fdevices-manifest%2Fopenconfig-terminal-device-properties.yang

AP: @EstherLerouzic : to modify the description for penalty .

**Comment by ggalimba56** [comment]
I agree with Esther suggestion

**Comment by sergiobelotti** [comment]
> I agree with Esther suggestion
@EstherLerouzic @ggalimba56 : is this one the definition you suggested ? 
leaf penalty-value {
      type decimal64 {
        fraction-digits 2;
      }
      units dB;
      description
        "OSNR penalty associated to the given values, expressed in dB.";
    }
  }

**Comment by EstherLerouzic** [comment]
What about this definition:
 description "OSNR penalty associated to the given impairment on the receiver, expressed in dB"

**Comment by EstherLerouzic** [comment]
Rewording from Dieter: "OSNR penalty associated with the related optical impairment at the receiver, expressed in dB"
