### ISSUE TITLE
Frequency Range clarification

### ISSUE THREAD

**Issue by ggalimba56** [ietf-ccamp-wg/ietf-ccamp-layer0-types-ext#46]
If the below definition is referred to the portin od spectrum assigned to a Media Channel (or OTSi)

```
  grouping frequency-range {
    description
      "The parameters that define a frequency range.";
    leaf lower-frequency {
      type frequency-thz;
      mandatory true;
      description
        "The lower frequency boundary of the
        frequency range.";
    }
    leaf upper-frequency {
      type frequency-thz;
      must '. > ../lower-frequency' {
        error-message
          "The upper frequency must be greater than the lower
          frequency.";
      }
      mandatory true;
      description
        "The upper frequency boundary of the
        frequency range.";
    }
  }
```

instead of using the frequency range as high - low frequency, I'd prefer tu use "m" * slot granularity
In addition  there is not the Media channel definition that is a topic part of L0 (in ROADMs)

Clarify in DT and fix

**Comment by sergiobelotti** [comment]
Call on 05/24/22:
we all agree to go for the modification proposed.
AP: @sergiobelotti @italobusi : to modify the description during next PR
